language: java
addons:
  sonarcloud:
    organization: "lvcarnevalli-github"
install: 
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f app/pom.xml
script: 	
  - mvn test -B -f app/pom.xml
  - mvn sonar:sonar -B -f app/pom.xml