language: java
addons:
  sonarcloud:
    organization: "lvcarnevalli-github"
install: 
  - mvn clean install -Dmaven.javadoc.skip=true -B -V -f app/pom.xml
script: 	
  - mvn clean verify -B -f performance-test/pom.xml
  - mvn clean verify -B -f component-test/pom.xml
  - mvn clean verify -B -f security-test/pom.xml
after_success:
  - mvn sonar:sonar -B -f app/pom.xml