version: "3.3"
services:
  mocks:
    build: ../dependencies/stubby/
    ports:
    - "9001:9001"
    - "9002:9002"
    - "9003:9003"
  redis:
    image: redis:5.0.5-alpine
    ports:
    - "6379:6379"
  app:
    build: ../
    depends_on:
    - mocks
    - redis
    ports:
    - "8080:8080"
    environment:
    - "SERVER_PORT:8080"
    - "clients_pokemon_endpoint=http://mocks:9001"
    - "ff4j_redis_server=redis"
    - "ff4j_redis_port=6379"