version: "3.3"
services:
  mocks:
    build: ../dependencies/mocks/
    ports:
    - "9001:9001"
    - "9002:9002"
    - "9003:9003"
  app:
    build: ../
    depends_on:
    - mocks
    ports:
    - "8080:8080"
    environment:
    - "SERVER_PORT:8080"
    - "clients_pokemon_endpoint=http://mocks:9001"